---
- name: Setup Debian nginx
  include: Dedian.yaml
  when: ansible_os_family == 'Debian'

- name: Setup RedHat nginx
  include: RedHat.yaml
  when: ansible_os_family == 'RedHat'

- name: Setup Startpage INDEX.HTML
  include: Startpage.yaml
  
- name: Testin HTTP Connect
  include: Check.yaml