ec_all:
  vars: 
    ansible_ssh_user: root
  children:
    work_hosts:
      hosts:
        work_01:
          ansible_host: 192.168.202.1
        work_02:
          ansible_host: 192.168.202.2
    workshop_hosts:
      hosts:
        work_shop_01:
          ansible_host: 192.168.201.1
    k8s:
      hosts:
        k8s_01:
          ansible_host: 192.168.203.1
        k8s_02:
          ansible_host: 192.168.203.2
jump:
  hosts:
    ec_jump:
      ansible_host: 178.124.206.53

