apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: leasing-test

resources:
  - leasing-app-blue.yaml
  - leasing-app-green.yaml
  - leasing-app-service.yaml
  - leasing-app-ingress.yaml
  - leasing-app-secret.yaml

configMapGenerator:
  - name: leasing-app-config
    envs:
      - app.env

generatorOptions:
  disableNameSuffixHash: true