apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: leasing-app
  namespace: leasing-test
spec:
  rules:
    - host: leasing-test.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: leasing-app
                port:
                  number: 80
