---
- name: Nginx. Install packages
  apt:
    name: "{{ apt_nginx_packages }}"
    state: present
    update_cache: yes
- name: Nginx. Enable and start servce
  service:
    name: nginx
    state: started
    enabled: yes