apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: leasing-test
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "leasing-app"
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - leasing-app.leasing-test.svc.cluster.local:80
