alertmanager:
  enabled: true
  config:
    global:
      slack_api_url: 'Slack Webhook Url'
    route:
      group_by: ['alertname', 'cluster']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'slack-default'
      routes:
        - match:
            alertname: NodeHighCpuUsage
          receiver: slack-default
        - match:
            alertname: NodeHighMemoryUsage
          receiver: slack-default
        - match:
            severity: critical
          receiver: slack-critical
          repeat_interval: 30m
    receivers:
      - name: 'slack-default'
        slack_configs:
          - channel: '#all-alerts'
            send_resolved: true
            title: "{{ .GroupLabels.alertname }}"
            text: |-
              {{ range .Alerts }}
              *–û–ø–æ–≤–µ—â–µ–Ω–∏–µ:* {{ .Annotations.summary }}
              *–û–ø–∏—Å–∞–Ω–∏–µ:* {{ .Annotations.description }}
              *Node:* {{ .Labels.instance }}
              *Pod:* {{ .Labels.pod }}
              *–í—Ä–µ–º—è:* {{ .StartsAt }}
              *–í–∞–∂–Ω–æ—Å—Ç—å:* {{ .Labels.severity }}
              {{ end }}

      - name: 'slack-default'
        slack_configs:
          - channel: '#all-alerts'
            send_resolved: true
            title: "‚ö†Ô∏è WARNING: {{ .GroupLabels.alertname }}"
            color: 'warning'
            text: |-
              {{ range .Alerts }}
              *–û–ø–æ–≤–µ—â–µ–Ω–∏–µ:* {{ .Annotations.summary }}
              *–û–ø–∏—Å–∞–Ω–∏–µ:* {{ .Annotations.description }}
              *Node:* {{ .Labels.instance }}
              *Pod:* {{ .Labels.pod }}
              *–í—Ä–µ–º—è:* {{ .StartsAt }}
              *–í–∞–∂–Ω–æ—Å—Ç—å:* {{ .Labels.severity }}
              {{ end }}

      - name: 'slack-critical'
        slack_configs:
          - channel: '#critical-alerts'
            send_resolved: true
            title: "üö® CRITICAL: {{ .GroupLabels.alertname }}"
            color: 'danger'
            text: |-
              {{ range .Alerts }}
              *–û–ø–æ–≤–µ—â–µ–Ω–∏–µ:* {{ .Annotations.summary }}
              *–û–ø–∏—Å–∞–Ω–∏–µ:* {{ .Annotations.description }}
              *Node:* {{ .Labels.instance }}
              *Pod:* {{ .Labels.pod }}
              *–í—Ä–µ–º—è:* {{ .StartsAt }}
              *–í–∞–∂–Ω–æ—Å—Ç—å:* {{ .Labels.severity }}
              {{ end }}

