---
- name: MySQL. Install and setup
  template:
    src: my.cnf.j2
    dest: ~/.my.cnf
    owner: root
    mode: 0600
  notify:
    - mysql restart

- meta: flush_handlers

- name: Configuring encoding DB
  mysql_db:
    name: "{{ app_db_name }}"
    encoding: utf8

- name: Configuring user priviliges
  mysql_user:
    name: User name "{{ app_db_user }}"
    password: "{{ app_db_pass }}"
    priv: "{{ app_db_name }}.*:ALL"

- name: Config database
  template:
    src: database.yml.j2
    dest: "{{ app_home }}/config/database.yml"
