---
- name: MySQL.Install
  block:
    - template:
        src: .my.cnf
        dest: ~/.my.cnf
        owner: root
        mode: 0600
    - service:
        name: mysql 
        state: started
        enabled: yes
  tags:
  - mysql::setup

- name: MySQL. Create DB
  mysql_db:
   name: "{{ app_db_name  }}"
   encoding: utf8
  tags:
  - mysql::setup

- name: MySQL. Create user
  mysql_user:
    name: "{{ app_db_user }}"
    password: "{{app_db_pass}}"
    priv: "{{ app_db_name  }}.*:ALL"
  tags:
  - mysql::setup

- name: Redmine. Clone repo
  git:
    repo: "{{ app_repo_name }}"
    dest: "{{ app_home }}"
    version: "{{ app_version }}"
    accept_hostkey: yes
  tags:
  - redmine::repo

- name: Redmine. DB cfg copy
  template:
    src: database.yml.j2
    dest: "{{ app_home }}/config/database.yml"


- name: Redmine. Change permissions
  file:
      path: "{{ app_home }}/public"
      owner: www-data
      group: www-data
      recurse: yes

- name: Redmine. DB template
  template:
    src: database.yml.j2
    dest: "{{ app_home }}/config/database.yml" 
  tags:
  - redmine::db_template

- name: Readmine. Setup Bundler
  shell: |
    gem install bundler
    bundle update   
  args:
    executable: /bin/bash
    chdir: "{{ app_home }}"
  tags: 
  - setup

- name: Session store secret generation
  shell: rake generate_secret_token
  args:
   chdir: "{{ app_home }}"
   creates: "{{ app_home }}/config/initializers/secret_token.rb"
  tags:
  - setup

- name: Readmine. Bundler Part 2
  shell: | 
    bundle exec rake db:migrate RAILS_ENV=production 
    bundle exec rake redmine:plugins:migrate RAILS_ENV=production
    bundle install --without development test
    RAILS_ENV=production rake db:migrate
    RAILS_ENV=production REDMINE_LANG="{{ app_lang }}" rake redmine:load_default_data
    #bundle exec rails server webrick -e production
  args:
    chdir: "{{ app_home }}" 
  tags:
  - setup
