---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-joomla
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-alias: "joomla-sa.k8s-XX.sa"
spec:
  rules:
    - host: joomla-sa.k8s-XX.sa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sa-joomla
                port:
                  number: 80
