---
- name: Nginx. Install packages
  yum:
    name: "{{ yum_http_packages }}"
    state: present

- name: Nginx. Remove welcome file
  file:
    path: "/usr/share/nginx/html/index.html"
    state: absent

- name: Nginx. Enable and start servce
  service:
    name: nginx
    state: started
    enabled: yes