apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ci

resources:
  - ci-namespace.yaml
  - jenkins/jenkins-pvc.yaml
  - jenkins/jenkins-deployment.yaml
  - jenkins/jenkins-service.yaml
  - jenkins/jenkins-ingress.yaml
