---
apt_redmine_packages:
  - git
  - ruby-full
  - build-essential
  - libmysqlclient-dev
  - imagemagick
  - libmagickwand-dev
  - apache2
  - libapache2-mod-passenger
  - mysql-server
  - mysql-client
  - python-pymysql

app_db_host: localhost
app_db_name: redmine
app_db_user: redmine
app_db_pass: redmine

app_repo_name: "https://github.com/redmine/redmine.git"
app_home: /opt/redmine
app_version: 4.0-stable
app_lang: "en"
app_fqdn: "redmine.my" 