- name: Install EPEL Repo
  yum:
    name: epel-release
    state: present

- name: Nginx. Install packages
  yum:
    name: nginx
    state: present

- name: Nginx. Enable and start service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Nginx. Deploy centos
  vars:
    html_dir: "{{ centos_nginx_html_dir }}"
    virtual_hosts: "{{ centos_virtual_hosts }}"
  include_tasks: deploy.yaml
  with_items: "{{ virtual_hosts }}"

- name: Restart nginx centos
  service:
    name: nginx
    state: restarted

- name: Nginx. Enable firewall port
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled

- name: Nginx. reload service firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Nginx. Test centos
  vars:
    virtual_hosts: "{{ centos_virtual_hosts }}"
  include_tasks: test.yaml
  with_items: "{{ virtual_hosts }}"
