---
- name: Check content to the sites
  uri:
    url: "http://127.0.0.1"
    headers:
      Host: "{{ item }}"
    return_content: yes
  register: this
  failed_when: "'Welcome' not in this.content"


- name: Print output
  debug:
    msg: "Host: {{ item }}"

