ubuntu:
  hosts:
    host_2:
      ansible_host: 192.168.203.14
    host_4:
      ansible_host: 192.168.203.16
RHEL:
  hosts:  
    host_1:  
      ansible_host: 192.168.203.13
    host_3:  
      ansible_host: 192.168.203.15
    host_5:  
      ansible_host: 18.194.96.246        
nginx:
  vars:
    ansible_user: updater
    site01: "local_test01.org"
    site02: "local_test01.ru"
    virtual_domain:
      - { name: "{{ site01 }}", ip: "localhost" }
      - { name: "{{ site02 }}", ip: "localhost" }
  children:
    internal:
      hosts:
        host_2:
        host_3: 
        
nginx_on_aws:
  vars:
    ansible_user: updater 
    site_aws: "localhost"
    virtual_hosts: 
      - { name: "{{ site_aws }}", ip: "172.31.32.227" }
  children:
    int: 
      hosts:
        host_5: 
