---
# preset steps.
- name: install utils for Deb
  apt:
    name:
    - curl
    - gnupg2
    - ca-certificates
    - lsb-release
    state: present
# To set up the apt repository for stable nginx packages
- name: run preset script for install nginx repository
  script: preset_script.sh
    

- name: apt remove the Apache package
  apt:
    name: apache2
    state: absent

# Install nginx
- name: apt nginx. Install packages.
  apt:
    name: "{{ apt_nginx_packages }}"
    state: present
    update_cache: yes
# Enable and start nginx 
- name: Deb nginx. Enable and start service
  service:
    name: nginx
    state: started
    enabled: yes

