---
apt_redmine_packages:
  - git
  - ruby-full
  - build-essential
  - libmysqlclient-dev
  - imagemagick
  - libmagickwand-dev
  - apache2
  - libapache2-mod-passenger
  - mysql-server
  - mysql-client
  - python-pymysql
  - python-mysqldb
  - python-apt