---
- name: apt | update repository cache
  apt:
    update_cache: yes
  tags: setup
- name: Redmine. Install packages
  apt:
    name: "{{ apt_redmine_packages }}"
    state: latest

- name: Install Redmine
  import_tasks: install.yaml
  when: install_type == "setup"

- name: upgrade Redmine
  import_tasks: update.yaml
  when: install_type == "update"
