- name: Configuration files for virtualhost
  template:
    src: templates/redmine.site.conf.j2
    dest: "/etc/apache2/sites-enabled/redmine.site.conf"
  notify:
    - apache2 restart
  tags:
    - apache::setup

- meta: flush_handlers

- name: "Add {{ app_fqdn }} to host file"
  shell: echo "127.0.0.1       {{ app_fqdn }}" >> /etc/hosts
  tags:
    - test

- name:  "Test {{ app_fqdn }}" 
  uri:
    url: "http://{{ app_fqdn }}"
    return_content: yes
  register: this
  failed_when: "'Jean-Philippe Lang' not in this.content"
  tags:
    - test

- name: Clearn host file      
  lineinfile:
    path: /etc/hosts
    state: absent
    regexp: '^127.0.0.1       {{ app_fqdn }}'
  tags:
    - test
