all_workers:
        children:
                work_sa:
                        hosts:
                                host15:
                                        ansible_host: 192.168.202.15
                                host16:
                                        ansible_host: 192.168.202.16
jump_sa:
   vars:
      env: "it-academy"
   hosts:
           bastion:
                   ansible_host: 178.124.206.53
                   ansible_user: jump_sa      
