---
- name: Install Nginx on Ubuntu
  apt:
    name: "{{ apt_nginx_packages }}"
    state: present
- name: Enable and start Nginx service on Ubuntu
  service:
    name: nginx
    state: started
    enabled: yes
