---
apt_redmine:
  - git
  - ruby-full
  - build-essential 
  - libmysqlclient-dev 
  - imagemagick 
  - libmagickwand-dev
  - apache2 
  - libapache2-mod-passenger
  - mysql-server 
  - mysql-client
  - python-pymysql
  - ruby2.4
  - ruby2.4-dev

#deb:
#  - python-pymysql_0.7.2-1ubuntu1_all.deb

app_db_name: redmine
app_db_user: redmine
app_db_pass: redmine
app_db_host: "127.0.0.1"

app_repo: https://github.com/redmine/redmine.git
app_vers: 4.0-stable
app_home: /opt/redmine
app_lang: "ru"
app_fqdn: "redmine.lan"
