services:
  webserver:
    image: nginx
    container_name: webserver
    ports:
    - "127.0.0.1:81:80"
    volumes:
    - ./app:/usr/share/nginx/html:ro
  nginx_svc:
    image: nginx
    container_name: nginx-nfs
    ports:
      - "8100:80"
    volumes:
      - data_nfs:/usr/share/nginx/html:ro
volumes:
  data_nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.204.85,rw,nolock,hard,nointr,nfsvers=4"
      device: ":/tmp/data/"

