---
- name: Mysql. Install packages
  apt:
    name: "{{ apt_mysql_packages }}"
    state: latest
    update_cache: yes

- name: MySQL. Install and setup
  template:
    src: my.cnf.j2
    dest: ~/.my.cnf
    owner: root
    mode: 0600
  notify:
    - restart mysql

- meta: flush_handlers

- mysql_db:
    name: "{{ app_db.name }}"
    encoding: utf8

- mysql_user:
    name: "{{ app_db.user }}"
    password: "{{ app_db.pass }}"
    priv: "{{ app_db.name }}.*:ALL"
#    no_log: "{{ hide_logs | default(True) }}"
