---
- name: Add nginx to jenkins group
      shell: |
        usermod -aG jenkins nginx

- name: Set httpd_can_network_connect
      shell: |
        setsebool -P httpd_can_network_connect 1

- name: Register Jenkins initial password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: key

- name: Show Jenkins password
      debug:
        msg: "{{ key.stdout }}"
- name: Install uti
  yum:
    name: "{{ utilities }}"

- name: Add repo
  get_url:
    url: 'https://pkg.jenkins.io/redhat-stable/jenkins.repo'
    dest: '/etc/yum.repos.d/jenkins.repo'

- name: Import key
  rpm_key:
    key: 'https://pkg.jenkins.io/redhat-stable/jenkins.io.key'
    state: present

- name: Install Jenkins
  yum:
    name: jenkins

- name: Start Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes
