---
#- name: HTTPD. Remove packages
#  yum:
#    name: "{{ yum_http_packages }}"
#    state: absent
#
- name: HTTPD. Install packages
  yum:
    name: "{{ yum_http_packages }}"
    state: present

- name: HTTPD. Remove welcome file
  file:
    path: "/etc/httpd/conf.d/welcome.conf"
    state: absent

- name: HTTPD. Enable and start servce
  service:
    name: httpd
    state: started
    enabled: yes
