---
apt_redmine_packages: 
  - git
  - ruby-full
  - build-essential
  - libmysqlclient-dev
  - imagemagick
  - libmagickwand-dev
  - apache2
  - libapache2-mod-passenger
  
app_repo: "https://github.com/redmine/redmine.git"
app_home: /opt/redmine
app_version: 4.1-stable
app_lang: "ru"
app_fqdn: "redmine-6.sa"
