---
- name: Nginx. Install packages
  yum:
    name: "{{ yum_nginx_packages }}"
    state: present
- name: Nginx. Enable and start servce
  service:
    name: nginx
    state: started
    enabled: yes