---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-config
data:
  index.html: |
    <html>
      <head>
        <title>{{POD_NAME}}</title>
      </head>
      <body>
        <h3>Hello from pod {{POD_NAME}}</h3>
        <p><script>document.write(`Current UTC time: ${new Date().toISOString()}`);</script></p>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      initContainers:
      - name: init-create-index-html
        image: busybox:1.28
        command: ['sh', '-c', "sed \"s/{{POD_NAME}}/$(hostname)/g\" /tmp/index.html > /data/index.html"]
        volumeMounts:
        - name: index-html-config-mount
          mountPath: /tmp/index.html
          subPath: index.html
        - name: data-volume-mount
          mountPath: /data
      containers:
      - name: nginx-server
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: data-volume-mount
          mountPath: "/usr/share/nginx/html"
        - name: ssh-keys-pair-mount
          mountPath: "/root/.ssh"
      volumes:
      - name: index-html-config-mount
        configMap:
          name: index-html-config
      - name: data-volume-mount
        emptyDir: {}
      - name: ssh-keys-pair-mount
        secret:
          secretName: secret-ssh-keys-pair
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 4

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    run: nginx-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx-test
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sa
  annotations:
    nginx.ingress.kubernetes.io/server-alias: "nginx-test.k8s-14.sa"
spec:
  ingressClassName: nginx
  rules:
    - host: nginx-test.k8s-13.sa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
